### ISSUE TITLE
Semantic similarity vs NLI

### ISSUE THREAD

**Issue by hossein-amirkhani** [m3hrdadfi/sentence-transformers#1]
Hi, thanks for your efforts as well as your interest in FarsTail. 

Even though this is a useful resource for the semantic similarity task, it is different from NLI. It is correct to say that close sentences in the same paragraphs are semantically similar, but they do not necessarily have the "entailment" relation. Similarly, the far sentences can be considered thematically different, but not the "contradiction" ones. I suggest replacing the entailment (contradiction) terms with similar (dissimilar).

**Comment by m3hrdadfi** [comment]
Thank you!

Yes, you're right. It's actually considered the thematic relation than the entailment one. I just defined the name for making things simple. I'd change it soon.
