### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by hossein-amirkhani** [m3hrdadfi/sentence-transformers#2]
Hi,
I did not get the point of the following sentence. Can you please clarify it?
"However, the model could be achieved remarkable results on recognizing entailment (81.71%) in contrast to what they mentioned in their paper (78.13%), still not adequate for NLI applications."

**Comment by m3hrdadfi** [comment]
In fact, the trained Sentence-Transformer model by FarsTail was not able to achieve good results on NLI applications, which I specified in README, like the Semantic Search, Text Summarization. Although the sequence classification model using ParsBERT shows good results in recognizing the entailment/contradiction task.
