### ISSUE TITLE
Pars-BERTopic

### ISSUE THREAD

**Issue by zahra606** [m3hrdadfi/sentence-transformers#3]
I wanted to use this model for the topic modeling but the words in each topic are marked with English letters.

 What is the reason?
![Capture](https://user-images.githubusercontent.com/74651083/103794827-74b17e00-505a-11eb-852a-81b6a3044074.JPG)

**Comment by m3hrdadfi** [comment]
BERTopic has upgraded its code to another version that is incompatible with the current Topic Modeling example. You just need to downgrade your BERTopic to 0.3.2.

Replace this piece of code 

```bash
!pip install -qU bertopic
```
with this

```bash
!pip install -q bertopic==0.3.2
```

**Comment by zahra606** [comment]
I executed this command and the problem was solved. Thank you for your guidance
