### ISSUE TITLE
Error in importing libs

### ISSUE THREAD

**Issue by tadeha** [m3hrdadfi/sentence-transformers#4]
As the topic modeling Colab example, I've used the following versions of the libraries:
```
!pip install -qU sentence-transformers==0.3.9
!pip install -q bertopic==0.3.2
```

But unfortunately, when Colab tries to import it, it runs to the error below:
<img width="791" alt="Screen Shot 2021-05-23 at 13 08 58" src="https://user-images.githubusercontent.com/22890731/119253782-1085f580-bbc8-11eb-9b37-7e1e9f84c72d.png">

**Comment by m3hrdadfi** [comment]
@tadeha 

It is now resolved!

**Comment by m3hrdadfi** [comment]
@tadeha,

In case of having the same problem, feel free to reopen the issue.

**Comment by FatemehMashhadi** [comment]
Hi,
As the Semantic_Search Colab example, the versions of required libraries are not compatible.
Please specify the required versions.

```
!pip install -qU sentence-transformers==1.2.0
!pip install -qU wikipedia-api
!pip install -qU hazm==0.5
!pip install -qU clean-text[gpl]
!pip install -qU emoji==1.7
!pip install nltk==3.0.2
!pip install numpy==1.23.0
```
